/* Reusable Resolve shell and real menu states, measured from the supplied recording.
 * All displayed media thumbnails come from that recording. No generated UI result.
 */
(function(){
 const STR={en:{playback:'Playback',deleteCache:'Delete Render Cache',renderCache:'Render Cache',all:'All…',unused:'Unused…',selected:'Selected Clips…',confirm:'Delete Project Cache?',warning:"This will delete all render cache in this project. You can’t undo this action.",cancel:'Cancel',delete:'Delete'}};
 function build(root,base='assets/'){
  root.className='resolve-ui';root.innerHTML=`<div class="rv-menubar"><span>DaVinci Resolve</span><span>File</span><span>Edit</span><span>Trim</span><span>Timeline</span><span>Clip</span><span>Mark</span><span>View</span><span id="rv-playback">Playback</span><span>Fusion</span><span>Color</span><span>Fairlight</span><span>Workspace</span><span>Help</span></div><div class="rv-toolbar">▣ Media Pool <span>Effects</span><span>Index</span><span>♫ Sound Library</span><span>Keyframes</span></div><div class="rv-title">DDR 2.0</div><div class="rv-bin">▾ Bins<span>Master</span><br><br><br><br><br><span>Smart Bins</span><span>Keywords</span><span>Collections</span></div><div class="rv-pool"><div class="rv-tab">Master</div><img src="${base}pool_strip.png"></div><div class="rv-tools">↖ ▣ ◇ ⌁ ♫ ⛓ ⚑ ◀</div><div class="rv-timeline"><div class="rv-ruler">01:00:23:01 01:00:16:00 01:00:32:00 01:00:48:00</div><div class="rv-cache"></div><div class="rv-tracklabel">V1<br>Video 1</div><img class="rv-trackimg" src="${base}timeline_strip.png"><div class="rv-playhead"></div></div><div class="rv-viewer"><img src="${base}offline_viewer.png"></div><div class="rv-inspector"><b>Video</b><b>▾ Transform</b><span>Zoom　　　　 1.000　1.000</span><span>Position　　　 0.000　0.000</span><span>Rotation Angle　　　 0.000</span><span>Anchor Point　 0.000　0.000</span><b>▸ Cropping</b><b>▸ Dynamic Zoom</b><b>▾ Composite</b><span>Composite Mode　 Normal</span><span>Opacity　　　　　 100.00</span><b>▸ Speed Change</b><b>▸ Stabilization</b><b>▸ Lens Correction</b><b>▸ Retime and Scaling</b></div><div class="rv-scrub">◀ ◁ ▷ ▶ ↻</div><div class="rv-bottom"><span>Media</span><span>Cut</span><span class="rv-active">Edit</span><span>Fusion</span><span>Color</span><span>Fairlight</span><span>Deliver</span></div>`;
 }
 function buildMenu(root){root.className='resolve-menu';root.innerHTML=`<div class="menu-row muted"><span class="check">✓</span>Use Optimized Media if Available</div><div class="menu-row muted">Proxy Handling <span class="arrow">›</span></div><div class="menu-separator"></div><div class="menu-row muted">Timeline Playback Resolution <span class="arrow">›</span></div><div class="menu-row muted">Photo Album Preview Resolution <span class="arrow">›</span></div><div class="menu-separator"></div><div class="menu-row" data-key="render">Render Cache <span class="arrow">›</span></div><div class="menu-row" data-key="delete">Delete Render Cache <span class="arrow">›</span></div><div class="menu-row muted">Manage Render Cache…</div><div class="menu-separator"></div><div class="menu-row muted">Fusion Memory Cache <span class="arrow">›</span></div>`;}
 function set(root,s={}){root.querySelectorAll('[data-key]').forEach(x=>x.classList.toggle('focus',x.dataset.key===s.highlight));}
 window.ResolveUI={STR,build,buildMenu,set};
})();
